update workflows

diff --git a/.github/workflows/code_quality.yml b/.github/workflows/code_quality.yml
--- a/.github/workflows/code_quality.yml
+++ b/.github/workflows/code_quality.yml
@@ -2,14 +2,23 @@ name: Code Quality
 
 on:
   push:
-    branches: [ main ]
+    branches: [ main, develop ]
   pull_request:
-    branches: [ main ]
+    branches: [ main, develop ]
 
 jobs:
   analyze:
     runs-on: ubuntu-latest
     steps:
+      - name: Verify SDK compatibility
+        run: |
+          CURRENT_DART_VERSION=$(dart --version | grep -o '[0-9]\.[0-9]\.[0-9]')
+          REQUIRED_DART_VERSION="3.2.3"
+          if [ "$(printf '%s\n' "$REQUIRED_DART_VERSION" "$CURRENT_DART_VERSION" | sort -V | head -n1)" != "$REQUIRED_DART_VERSION" ]; then
+            echo "Current Dart version $CURRENT_DART_VERSION is less than required $REQUIRED_DART_VERSION"
+            exit 1
+          fi
+
       - uses: actions/checkout@v3
       
       - name: Setup Flutter
